apiVersion: v2
name: microservice
description: Microservices' charts for VotingBooth
type: application
version: 0.1.0
dependencies:
  - name: common
    version: 0.1.0
    repository: "file://../common"