apiVersion: v2
name: vote-api
description: vote-api charts for VotingBooth
type: application
version: 0.1.0
dependencies:
  - name: common
    version: 0.1.0
    repository: https://jerodd.github.io/VotingBooth-Helm