{{- if and .Values.sealedSecrets .Values.sealedSecrets.vars }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  encryptedData:
    {{- range $k, $v := .Values.sealedSecrets.vars }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
{{- end }}
